# air setup for hotreloading (dev frontapp)
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main.exe cmd/front/main.go"
bin = "tmp/main.exe"

include_ext = ["go", "html", "css", "js"] # watch these filename extensions
#ignore these filename extentions or dirs
exclude_dir = ["assets", "data", "build", "deployments", "pkg", "vendor", "tmp", "internal\\utils"]

include_dir = ["internal/front/web/templates", "internal/front"]
include_file = []

log = "air.log"
poll_internval = 200 #ms 
delay = 100 #ms 
stop_on_error = true





[log]
# show log time
time = false
main_only = false
silent = false


[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# delete tmp dir on exit
clean_on_exit = false

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
proxy_port = 8081
app_port = 8080




# ref https://github.com/air-verse/air/blob/master/air_example.toml